"""Tunable knobs and canned safe responses for the guardrail/evaluator graph.

Centralised so latency/cost trade-offs (retry budget, judge on/off) and the
user-facing safety copy live in one reviewable place.
"""

import os


# Max generate -> validate/judge -> retry loops before falling back. The spec
# caps this to prevent infinite regeneration loops on persistently bad output.
MAX_RETRIES = 2

# The LLM judge passes a reply whose accuracy score is at or above this.
JUDGE_ACCEPT_SCORE = 0.6

# Hard ceiling on accepted user input length (characters) before we treat it as
# a malformed / resource-abuse payload.
MAX_INPUT_CHARS = 4000


# Canned, safe responses (never generated by the model, so they can't be gamed).
INJECTION_REFUSAL = (
    "I can't help with that request. I stick to managing your schedule, tasks, "
    "and email — tell me what you'd like to do there and I'll take care of it."
)

MALFORMED_INPUT_REFUSAL = (
    "I couldn't read that request. Could you rephrase it a little more clearly?"
)

GENERATION_FALLBACK = (
    "I'm not confident I got that right, so I'd rather not guess. Could you "
    "rephrase what you need, or give me a bit more detail?"
)

# Substituted for any stored/retrieved context value (a task title, event
# summary, or past message) that trips an injection signature, so the payload
# never reaches the model while the item's ID stays usable.
REDACTED_CONTEXT = "[content withheld by guardrail]"


def judge_enabled() -> bool:
    """Whether the LLM-as-a-judge node should make its evaluation call.

    On by default (production). Set GUARDRAILS_JUDGE_DISABLED=1 to turn it off
    without a code change — the offline test suite does this in conftest so the
    judge never makes a real model call, while the deterministic input and output
    guardrails ALWAYS run regardless of this flag.
    """
    return os.getenv("GUARDRAILS_JUDGE_DISABLED", "").strip().lower() not in {"1", "true", "yes"}
